### ISSUE TITLE
Add a cheatsheet for `[].filter` method

### ISSUE THREAD

**Issue by KonstantinSimeonov** [latrovalievioan/learning2code#2]
Describe a couple common use cases, like:
- filtering odd/even numbers
- filtering empty strings or falsy values from an array
- filtering an array of people whose first name is longer than 5 letters
- filtering by index - how to keep only every n-th element, how to drop every n-th element

**Comment by latrovalievioan** [comment]
Implemented [here](https://github.com/latrovalievioan/learning2code/blob/master/cheatshets/Filter.md)

**Comment by KonstantinSimeonov** [comment]
https://github.com/latrovalievioan/learning2code/blob/master/cheatshets/Filter.md#ex1-return-the-even-nums the filter function is wrong, because it does not use the correct comparison operator

**Comment by latrovalievioan** [comment]
Fixed [here] (https://github.com/latrovalievioan/learning2code/blob/master/cheatshets/Filter.md#ex1-return-the-even-nums)

**Comment by latrovalievioan** [comment]
Fixed [here](https://github.com/latrovalievioan/learning2code/blob/master/cheatshets/Filter.md#ex1-return-the-even-nums)

**Comment by KonstantinSimeonov** [comment]
noice
