### ISSUE TITLE
Add object property access cheatsheet

### ISSUE THREAD

**Issue by KonstantinSimeonov** [latrovalievioan/learning2code#3]
Give examples for:
- known property access
- dynamically computed property access
- accessing properties with awkward names `zdra-veyte`
- accessing properties of nested objects (also give an example about nested access which uses both known property access and dynamically computed property access)

**Comment by latrovalievioan** [comment]
Implemented [here](https://github.com/latrovalievioan/learning2code/blob/master/cheatshets/objectPropertyAccess.md)

**Comment by KonstantinSimeonov** [comment]
Noice
