### ISSUE TITLE
Research the array methods "some" and "every"

### ISSUE THREAD

**Issue by KonstantinSimeonov** [latrovalievioan/learning2code#4]
Create a cheatsheet which explains the use and difference between both. Also provide at least 3 examples for each method.

**Comment by latrovalievioan** [comment]
Array method every() cheat sheet [here](https://github.com/latrovalievioan/learning2code/blob/master/cheatshets/every.md)
Array method some() cheat sheet [here](https://github.com/latrovalievioan/learning2code/blob/master/cheatshets/some.md)

**Comment by KonstantinSimeonov** [comment]
add examples for empty arrays

**Comment by latrovalievioan** [comment]
Explanation for empty arrays for .every() method [here](https://github.com/latrovalievioan/learning2code/blob/master/cheatshets/every.md)
Explanation for empty arrays for .some() method [here](https://github.com/latrovalievioan/learning2code/blob/master/cheatshets/some.md)

**Comment by KonstantinSimeonov** [comment]
noice!
