### ISSUE TITLE
Fix isInRadius function from the filter excercises

### ISSUE THREAD

**Issue by KonstantinSimeonov** [latrovalievioan/learning2code#5]
The filter function is not correct, the thing you have is a check if the point is inside a square centered around (0, 0) and having a side of `2 * radius`.

**Comment by latrovalievioan** [comment]
Implemented [here](https://github.com/latrovalievioan/learning2code/blob/master/array-methods/filterEx3.js)

**Comment by KonstantinSimeonov** [comment]
Gj
